services:
  frontend:
    image: emc-mitglieder-frontend:1.1.1
    container_name: emc-mitglieder-frontend-prod
    restart: unless-stopped
    ports:
      - "9082:80"
    networks:
      - emc_net

networks:
  emc_net:
    external: true
