services:
  emc-mitglieder-backend-dev:
    image: emc-mitglieder-backend:dev
    container_name: emc-mitglieder-backend-dev
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - emc_net

networks:
  emc_net:
    external: true
