services:
  emc-mitglieder-backend-dev:
    image: emc-mitglieder-backend:dev
    container_name: emc-mitglieder-backend-dev
    restart: unless-stopped
    environment:
      DB_URL: jdbc:mariadb://mariadb/emc_mitglieder_dev
      DB_USERNAME: emc_backend_dev_rw
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - emc_net

networks:
  emc_net:
    external: true