services:
  frontend:
    image: emc-mitglieder-frontend:1.1.1-SNAPSHOT
    container_name: emc-mitglieder-frontend-dev
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - emc_net

networks:
  emc_net:
    external: true
