services:
  emc-mitglieder-backend-prod:
    image: emc-mitglieder-backend:prod
    container_name: emc-mitglieder-backend-prod
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - emc_net

networks:
  emc_net:
    external: true
